# Generated by Django 6.0.3 on 2026-04-07 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracker.category')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(verbose_name='Plan tarihi')),
                ('weekday', models.CharField(blank=True, max_length=20, verbose_name='Gün')),
                ('owner_group', models.CharField(blank=True, max_length=150, verbose_name='İş alanı / sorumlu')),
                ('section', models.CharField(choices=[('SON_TESLIM_GUNU', 'Son teslim günü'), ('YAPILMASI_PLANLANANLAR', 'Yapılması planlananlar')], max_length=30, verbose_name='Bölüm')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('details', models.TextField(blank=True, verbose_name='Detay')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Son teslim tarihi')),
                ('priority', models.CharField(choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek'), ('CRITICAL', 'Kritik')], default='MEDIUM', max_length=10, verbose_name='Öncelik')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tracker.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'İş kaydı',
                'verbose_name_plural': 'İş kayıtları',
                'ordering': ['-plan_date', 'is_completed', '-due_date', '-created_at'],
            },
        ),
    ]
