# Generated by Django 6.0.3 on 2026-04-07 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Ad soyad')),
                ('role', models.CharField(choices=[('RESPONSIBLE', 'Sorumlu'), ('WORKER', 'İş Alan')], max_length=20, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kişi',
                'verbose_name_plural': 'Kişiler',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='plan_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Plan tarihi'),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_tasks', to='tracker.person', verbose_name='Sorumlu'),
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_tasks', to='tracker.person', verbose_name='İş Alan'),
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='İlerleme notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='tracker.task', verbose_name='Görev')),
            ],
            options={
                'verbose_name': 'İlerleme kaydı',
                'verbose_name_plural': 'İlerleme kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
