# Generated by Django 5.2 on 2026-04-07 12:47

import django.db.models.deletion
from django.db import migrations, models


def _forward_convert_person_roles(apps, schema_editor):
    Person = apps.get_model('tracker', 'Person')
    Role = apps.get_model('tracker', 'Role')

    role_map = {}

    def _normalize_role_name(value):
        raw = (value or '').strip()
        if raw == 'RESPONSIBLE':
            return 'Sorumlu'
        if raw == 'WORKER':
            return 'İş Alan'
        return raw or 'Tanımsız'

    for person in Person.objects.order_by('pk'):
        role_name = _normalize_role_name(person.role)
        if role_name not in role_map:
            role_obj, _ = Role.objects.get_or_create(name=role_name)
            role_map[role_name] = role_obj.id

        person.role = str(role_map[role_name])
        person.save(update_fields=['role'])


def _backward_convert_person_roles(apps, schema_editor):
    Person = apps.get_model('tracker', 'Person')
    Role = apps.get_model('tracker', 'Role')

    role_lookup = {str(role.id): role.name for role in Role.objects.all()}
    for person in Person.objects.order_by('pk'):
        person.role = role_lookup.get(str(person.role), '')
        person.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_person_alter_task_plan_date_task_responsible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Rol adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roller',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['role__name', 'name'], 'verbose_name': 'Kişi', 'verbose_name_plural': 'Kişiler'},
        ),
        migrations.RunPython(_forward_convert_person_roles, _backward_convert_person_roles),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='tracker.role', verbose_name='Rol'),
        ),
    ]
